In [133]:
import numpy as np

In [134]:
test_array = np.array([1,4,5,"8"],float)
print(test_array)

[1. 4. 5. 8.]


In [135]:
print(type(test_array[3]))

<class 'numpy.float64'>


In [136]:
print(test_array.dtype)

float64


In [137]:
print(test_array.shape)

(4,)


In [138]:
matrix = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix,int).shape

(3, 4)

In [139]:
tensor_rank3 = [
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
]
np.array(tensor_rank3,int).shape

(4, 3, 4)

In [140]:
tensor_rank3 = [
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
]
np.array(tensor_rank3,int).ndim

3

In [141]:
np.array(tensor_rank3,int).size

48

In [142]:
np.array([[1,2,3.5],[4,5,6.5]],dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [143]:
np.array([[1,2,3.5],[4,5,6.5]],dtype=float)

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [144]:
import sys
np.array([[1,2,3.5],[4,5,6.5]],
         dtype=np.float64).itemsize

8

In [145]:
np.array([[1,2,3.5],[4,5,6.5]],
         dtype=np.float32).itemsize

4

In [249]:
x=np.array([[1,2,5,8],[1,2,5,8]])
x.shape

(2, 4)

In [250]:
x.reshape(-1,)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [251]:
x = np.array(range(8))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [252]:
# x.reshape(2,2) 오류
x.reshape(4,2) #이런식으로 크기를 맞춰야 함

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [156]:
x = np.array(range(8)).reshape(4,2)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [157]:
x.reshape(2,-1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [158]:
x.reshape(2,2,-1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [159]:
x=np.array(range(8)).reshape(2,2,2)
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [160]:
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [161]:
x = np.array([[1,2,3],[4,5,6]],int)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [162]:
x[0][0]

np.int64(1)

In [163]:
x[0,2]

np.int64(3)

In [164]:
x[0,1]=100
x

array([[  1, 100,   3],
       [  4,   5,   6]])

In [165]:
x=np.array([[1,2,3,4,5],[6,7,8,9,10]],int)
x[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [166]:
x[1,1:3]

array([7, 8])

In [167]:
x[1:3]

array([[ 6,  7,  8,  9, 10]])

In [168]:
x= np.array(range(15),int).reshape(3,-1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [169]:
x[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [170]:
x[::2,::3]

array([[ 0,  3],
       [10, 13]])

In [171]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [172]:
np.arange(-5,5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [173]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [174]:
np.ones(shape=(5,2),dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [175]:
np.zeros(shape=(2,3),dtype=np.float32)

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [176]:
np.empty(shape=(2,4),dtype=np.float32)

array([[0.    , 1.875 , 0.    , 2.25  ],
       [0.    , 2.3125, 0.    , 2.5   ]], dtype=float32)

In [177]:
x=np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [178]:
np.ones_like(x)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [179]:
np.zeros_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [180]:
np.identity(n=3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [181]:
np.identity(n=4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [182]:
np.eye(N=3,M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [183]:
np.eye(N=3,M=5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [184]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [185]:
np.diag(matrix)

array([0, 4, 8])

In [186]:
np.diag(matrix,k=1)

array([1, 5])

In [187]:
np.random.uniform(0,5,10)

array([2.65109636, 4.3770588 , 0.92740374, 1.21351734, 3.62012731,
       1.55738503, 1.76411002, 0.40618377, 2.72672246, 0.88057848])

In [188]:
np.random.normal(0,2,10)

array([ 0.60705314, -1.37095404,  0.71141808,  0.16225744,  0.35006625,
        5.08813345, -2.43314594, -3.06891201,  1.48291446,  7.05040272])

In [189]:
import numpy as np
test_array = np.arange(1,11)
test_array.sum()

np.int64(55)

In [190]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [191]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [192]:
test_array.sum(axis=1)

array([10, 26, 42])

In [193]:
test_array = np.arange(1,13).reshape(3,4)
third_order_tensor = np.array([test_array,test_array,test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [194]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [195]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [196]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [67]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [197]:
test_array.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [198]:
test_array.std()

np.float64(3.452052529534663)

In [199]:
test_array.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [200]:
np.sqrt(test_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [201]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.vstack((v1,v2))

array([[1, 2, 3],
       [4, 5, 6]])

In [202]:
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6])

In [203]:
v1 = v1.reshape(-1,1)
v2 = v2.reshape(-1,1)
v1

array([[1],
       [2],
       [3]])

In [204]:
v2

array([[4],
       [5],
       [6]])

In [205]:
np.hstack((v1,v2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [206]:
v1=np.array([[1,2,3]])
v2=np.array([[4,5,6]])
np.concatenate((v1,v2),axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [208]:
v1 = np.array([1,2,3,4]).reshape(2,2)
v2 = np.array([[5,6]]).T
v1

array([[1, 2],
       [3, 4]])

In [209]:
v2

array([[5],
       [6]])

In [210]:
np.concatenate((v1,v2),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [211]:
x=np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [212]:
x+x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [213]:
x-x

array([[0, 0, 0],
       [0, 0, 0]])

In [214]:
x/x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [215]:
x**x

array([[    1,     4,    27],
       [  256,  3125, 46656]])

In [216]:
x_1=np.arange(1,7).reshape(2,3)
x_2=np.arange(1,7).reshape(3,2)
x_1

array([[1, 2, 3],
       [4, 5, 6]])

In [217]:
x_2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [218]:
x_1.dot(x_2)

array([[22, 28],
       [49, 64]])

In [219]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [220]:
x+10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [221]:
x-2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [222]:
x//3

array([[0, 0, 1],
       [1, 1, 2],
       [2, 2, 3]])

In [223]:
x**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [224]:
x = np.arange(1,13).reshape(4,3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [225]:
v = np.arange(10,40,10)
v

array([10, 20, 30])

In [226]:
v = np.arange(10,40,10)
v

array([10, 20, 30])

In [227]:
x+v

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [228]:
import numpy as np
x = np.array([4,3,2,6,8,5])
x>3

array([ True, False, False,  True,  True,  True])

In [229]:
x=np.array([1,3,0])
y=np.array([2,1,7])
x>y

array([False,  True, False])

In [230]:
x=np.array([4,6,7,3,2])
(x>3)

array([ True,  True,  True, False, False])

In [231]:
(x>3).all()

np.False_

In [232]:
(x>3).any()

np.True_

In [233]:
(x<10).any()

np.True_

In [234]:
(x<10).all()

np.True_

In [235]:
(x>10).any()

np.False_

In [236]:
x = np.array([4,6,7,3,2])
x>5

array([False,  True,  True, False, False])

In [237]:
np.where(x>5)

(array([1, 2]),)

In [238]:
x = np.array([4,6,7,3,2])
np.where(x>5,10,20)

array([20, 10, 10, 20, 20])

In [239]:
x = np.array([4,6,7,3,2])
np.argsort(x)

array([4, 3, 0, 1, 2])

In [240]:
np.argmax(x)

np.int64(2)

In [241]:
np.argmin(x)

np.int64(4)

In [242]:
x = np.array([4,6,7,3,2])
x>3

array([ True,  True,  True, False, False])

In [243]:
cond = x>3
x[cond]

array([4, 6, 7])

In [244]:
x.shape

(5,)

In [245]:
cond.shape

(5,)

In [246]:
x = np.array([4,6,7,3,2])
cond = np.array([1,2,0,2,2,2,],int)
x[cond]

array([6, 7, 4, 7, 7, 7])

In [247]:
x.take(cond)

array([6, 7, 4, 7, 7, 7])

In [248]:
x = np.array([[1,4],[9,16]],int)
a = np.array([0,1,1,1,0,0],int)
b = np.array([0,0,0,1,1,1],int)
x[a,b]

array([ 1,  9,  9, 16,  4,  4])